### PR TITLE
Do the smart thing with gitignore

### PR DESCRIPTION
**Pull request by dbalatero**
As discussed on #11, here's a fix for gitignore/gitkeep.

### CODE REVIEW

**Comment by aaronjensen** [comment]
I think you can get rid of the gitkeep now since the gitignore will act as a gitkeep.

**Comment by dbalatero** [comment]
ugh missed that

**Comment by dbalatero** [comment]
> I think you can get rid of the gitkeep now since the gitignore will act as a gitkeep.

:green_heart: :sake: 6ca03ba

**Comment by aaronjensen** [comment]
thanks

**Pull request merged**
